version: '3.8'

services:
    cloud-api:
        build:
            context: ..
            dockerfile: ./docker/dockerfile
        container_name: cloud-api
        image: cloud-api
        ports:
            - 4000:4000
        env_file:
            - ../.env.prod
        networks:
            - cloud_api_network

networks:
    cloud_api_network:
        name: cloud_api_network
