version: '3.8'

services:
    cloud-api:
        image: bhaktibuana/cloud-api:latest
        container_name: cloud-api
        ports:
            - 4000:4000
        env_file:
            - ../.env.prod
        networks:
            - cloud_api_network
        volumes:
            - ../public:/app/public

networks:
    cloud_api_network:
        name: cloud_api_network

volumes:
    public:
        driver: local